### ISSUE TITLE
Adopt towncrier or similar

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-python#101]
As long as we are manually curating our changelog, it's just a matter of time until we miss something. We should adopt [towncrier](https://towncrier.readthedocs.io/en/actual-freaking-docs/) or a similar system to automate this.

**Comment by farleyb-amazon** [comment]
This continues to be relevant, but we're tracking it elsewhere as we look at improving changelog generation for all our ESDK implementations. Resolving.
