### ISSUE TITLE
Configuration information needed for decrypting Amazon Connect data

### ISSUE THREAD

**Issue by chamakov** [aws/aws-encryption-sdk-python#149]
Hi,

I'm trying to decrypt a string generated by AWS Connect, using aws-encryption-sdk-python, but I'm not able to do it, I'm receiving a "Decryption failed." Error every time.

I'm using a raw_key generator:

```python
def _get_raw_key(self, key_id):
        try:
            static_key = self._static_keys[key_id]
        except KeyError:
            # X.509 private key file
            static_key = open('blog.connect.private.key', 'rb').read()
            self._static_keys[key_id] = static_key
        return WrappingKey(
            wrapping_algorithm=WrappingAlgorithm.RSA_OAEP_SHA1_MGF1,
            wrapping_key=static_key,
            wrapping_key_type=EncryptionKeyType.PRIVATE
        )
```

Somebody can help me with this?

**Comment by mattsb42-aws** [comment]
Hi @chamakov,

You're almost there. The missing pieces are the values that Connect uses for the provider ID and key ID, as well as the wrapping algorithm they use. The below draft should point you where you need to go. Let us know if you still encounter issues.

```python
from aws_encryption_sdk.key_providers.raw import RawMasterKeyProvider, WrappingKey
from aws_encryption_sdk.identifiers import EncryptionKeyType, WrappingAlgorithm

class AmazonConnect(RawMasterKeyProvider):
    provider_id = "AmazonConnect"

    def _get_raw_key(self, key_id):
        # NOTE: key_id will be your contact flow ID
        static_key = load_my_key_from_wherever()
        return WrappingKey(
            wrapping_algorithm=WrappingAlgorithm.RSA_OAEP_SHA512_MGF1,
            wrapping_key=static_key,
            wrapping_key_type=EncryptionKeyType.PRIVATE,
        )
```

I will work with our docs teams to make sure that the Connect docs are updated to talk about this.

**Comment by chamakov** [comment]
Hi @mattsb42-aws,

It works like a charm!!, I have all day (Since 9 a.m.) working on this and I was so close to solve it, but I weren't able hehe.

Thanks a lot

**Comment by mattsb42-aws** [comment]
Great to hear you got this working!

I'll update here once we get the docs updated.

**Comment by mattsb42-aws** [comment]
For future readers, please see the updated Amazon Connect docs here:
https://docs.aws.amazon.com/connect/latest/adminguide/encrypt-data.html
