### ISSUE TITLE
Make frame length field in encryption materials request optional

### ISSUE THREAD

**Issue by ttjsu-aws** [aws/aws-encryption-sdk-python#175]
https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/materials_managers/__init__.py#L35

**Comment by mattsb42-aws** [comment]
We can't really do this because we need to maintain backwards compatibility. What we can do is make it no longer required.

**Comment by ttjsu-aws** [comment]
sgtm.

**Comment by mattsb42-aws** [comment]
Regarding what the value should be if it is not provided, I think that a reasonable backwards-compatible approach here would be to simply default it to the library-wide default frame length value.

https://github.com/aws/aws-encryption-sdk-python/blob/0f4dc6e7f695191daf3d8ceeef8786a93388259d/src/aws_encryption_sdk/internal/defaults.py#L23-L24

That will continue to allow CMMs that might have relied on the value being set to have a valid integer to work with.
