### ISSUE TITLE
RawAESKeyring MUST add signing keyring trace flags

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-python#181]
The Raw AES keyring uses the encryption context as AAD when encrypting the data key, so it MUST add:
* `WRAPPING_KEY_SIGNED_ENC_CTX` flag on encrypt
* `WRAPPING_KEY_VERIFIED_ENC_CTX` flag on decrypt

**Comment by 18AdrianoH** [comment]
https://github.com/aws/aws-encryption-sdk-python/pull/189 adds them.
