### ISSUE TITLE
Incorporate the encrypt test vectors and the decrypt oracle for each implementation in CI

### ISSUE THREAD

**Issue by seebees** [aws/aws-encryption-sdk-python#184]
Vectors are here: https://github.com/awslabs/aws-crypto-tools-test-vector-framework/tree/master/features/CANONICAL-GENERATED-MANIFESTS

* https://github.com/aws/aws-encryption-sdk-java
* https://github.com/aws/aws-encryption-sdk-python
* https://github.com/awslabs/aws-encryption-sdk-javascript

**Comment by farleyb-amazon** [comment]
Done as part of release earlier this year. Resolving.
