### ISSUE TITLE
Support crypto shredding based on the encryption context

### ISSUE THREAD

**Issue by ikben** [aws/aws-encryption-sdk-python#201]
(opening this issue to follow up on a conversation with Greg Rubin)
(note that I didn't look at KeyRings before writing this, so a lot of this might be solved by those)

I'm trying to build a solution that would leverage encryption to make data impossible to retrieve when a user would invoke its right to be forgotten (ie. [crypto shredding](https://en.wikipedia.org/wiki/Crypto-shredding)).

The "easy" ways to do that are unfortunately not ideal:

- We could create a KMS CMK for each user. This has the advantage that the there is no way to decrypt the data keys once the CMK has been deleted. The downsides is that this can become expensive rather fast (at $1 per user) and requires a new key every time a user signs up
- We could create one (or a few) CMKs and include the user-id in the encryption context. Decryption can than be prevented by editing the CMK policy and denying certain encryption contexts. The advantage here is that it's cost-effective and dynamic. The disadvantage are that someone with put-policy rights can re-enable access and you're limited by the maximum policy size.

If we want to have an irreversible deletion with only one key the only solution is the build our own master key provider. This is how that could work (I might be diving in too much of a solution here, the important part is the shredding, not the implementation):

```
my_ciphertext, encryptor_header = aws_encryption_sdk.encrypt(
    source=b'some-plaintext',
    key_provider=UserShreddingKeyProvider()
    encryption_context={
        'user': 'user-id-001',
    }
)
```

The KeyProvider will have to do the following:
- Check if there already exists a UserKeyCipherText (see below) for the given user and retrieve and decrypt it if so.
- If there is no existing UserKey: generate a key, encrypt this with the CMK. We will call this the UserKey and its respective UserKeyCipherText
- Store the UserKeyCipherText somewhere where it can be found by searching on user id.
- Generate a Data Key, encrypt it with the UserKey and return both the the encryption sdk

When you need to shred a user, you can delete its UserKeyCipherText and all the DataKeys will be useless.
As long as the user does not need to be shredded, you can open both enveloppes and get the plaintext.

The description above opens both enveloppes on the same machine. You can prevent leaking the UserKey by doing the encryption of the DK server side (like if the UserKey was a CMK)

You can also go a step further and generalize this to arbitrary tokens:

```
my_ciphertext, encryptor_header = aws_encryption_sdk.encrypt(
    source=b'some-plaintext',
    key_provider=TokenBasedKeyProvider()
    encryption_context={
        'token:user': 'user-id-001',
        'token:application': 'app-id-001',
    }
)
```

The idea is here that the plain text can only be used for the specific user-app combination and the shredding either of them must make the data not-decryptable. 

This could work like this:
- Generate (or retrieve) a Key for each field in the encryption context
- Generate a DK for each field and encrypt it under its respective key. Let's call these DKs our tokens.
- XOR all tokens and use that to encrypt the plaintext (and store all encrypted tokens so you can recontruct the DK by decrypting each token and XORing them again.

Deleting any Key will prevent the token from being decrypted and thus the plaintext will be not decrypted either.

**Comment by ikben** [comment]
I also found some example code I wrote based on a conversation i had last year with @benkehoe (he suggested the XORing explained above).

I didn't finish it, so it likely contains bugs, but it should give an idea of what the MasterKeyProvider could look like:

```python
import os
import typing
from functools import reduce

import attr
from aws_encryption_sdk.exceptions import EncryptKeyError
from aws_encryption_sdk.identifiers import Algorithm
from aws_encryption_sdk.key_providers.base import MasterKeyProvider, MasterKeyProviderConfig, MasterKeyConfig, MasterKey
from aws_encryption_sdk.structures import DataKey, EncryptedDataKey, RawDataKey

_PROVIDER_ID = "custom-token"


class TokenMasterKeyProviderConfig(MasterKeyProviderConfig):
    pass


class TokenMasterKeyProvider(MasterKeyProvider):
    provider_id = _PROVIDER_ID
    _config_class = TokenMasterKeyProviderConfig

    def __init__(self):
        # key_id should be the token endpoint
        if self.config.key_ids:
            self.add_master_keys_from_list(self.config.key_ids)

    def _new_master_key(self, key_id: bytes) -> MasterKey:
        return TokenMasterKey(config=TokenMasterKeyConfig(key_id=key_id))


@attr.s(hash=True)
class TokenMasterKeyConfig(MasterKeyConfig):
    provider_id = _PROVIDER_ID


class TokenMasterKey(MasterKey):
    provider_id = _PROVIDER_ID
    _config_class = TokenMasterKeyConfig

    def _generate_data_key(self, algorithm: Algorithm, encryption_context: dict) -> DataKey:
        # generate a data key.
        plaintext_data_key = os.urandom(algorithm.kdf_input_len)
        # encrypt the data key
        encrypted_data_key = self._encrypt_data_key(
            data_key=RawDataKey(key_provider=self.key_provider, data_key=plaintext_data_key),
            algorithm=algorithm,
            encryption_context=encryption_context,
        )
        return DataKey(
            key_provider=encrypted_data_key.key_provider,
            data_key=plaintext_data_key,
            encrypted_data_key=encrypted_data_key.encrypted_data_key,
        )

    def _encrypt_data_key(
            self, data_key: typing.Union[DataKey, RawDataKey], algorithm: Algorithm,
            encryption_context: dict
    ) -> EncryptedDataKey:

        # We xor all tokens, so order does not matter
        tokens = [self._get_token(type=k, id=v) for k, v in encryption_context.items() if k.startswith('token:')]
        if not tokens:
            raise EncryptKeyError('There should be at least one "token:*" key in the encryption context')

        key = reduce(lambda i, j: i ^ j, tokens)

        ciphertext = self._encrypt(data_key.data_key, key)

        return EncryptedDataKey(
            key_provider=self.key_provider, encrypted_data_key=ciphertext
        )

    def _decrypt_data_key(self, encrypted_data_key: EncryptedDataKey, algorithm: Algorithm,
                          encryption_context: dict) -> DataKey:
        plaintext = encrypted_data_key.encrypted_data_key

        return DataKey(
            key_provider=self.key_provider,
            data_key=plaintext,
            encrypted_data_key=encrypted_data_key.encrypted_data_key,
        )
    
    def _get_token(self, type, id):
        # this should call an external service to get a token
        raise NotImplementedError()
```

**Comment by mattsb42-aws** [comment]
Thanks for reaching out, @ikben 

I like the idea!

I'd like to move this over to our specification repo[1] to work on refining what this might look like with regards to feature additions.

We won't be doing any further feature expansion for the master key provider, but I think this has value as an idea for a keyring feature.

Thinking about this, I think I would break this down into a few necessary features that would create separate layers to this:

1. Tooling to define a key heirarchy and store intermediate keys.
2. A key selection mechanism to provide extension points for how to select the correct key.
3. A mechanism to select more than one key and combine them.

I think that layer 1 alone would be useful, as would layers 1+2, in addition to 1+2+3 doing what you described.

I'm not entirely sure what each of these layers should look like, but that's what the discussion we should have in the spec repo. :)

[1] https://github.com/awslabs/aws-encryption-sdk-specification

**Comment by mattsb42-aws** [comment]
I have created https://github.com/awslabs/aws-encryption-sdk-specification/issues/45 to discuss this feature request. I'm going to go ahead and close this issue, but please feel free to copy any information you think I missed over to that thread.
