### ISSUE TITLE
Support for symmetric encryption operations

### ISSUE THREAD

**Issue by benkehoe** [aws/aws-encryption-sdk-python#206]
Now that KMS [supports asymmetric keys](https://aws.amazon.com/blogs/security/digital-signing-asymmetric-keys-aws-kms/), it suffers from the same dilemma as symmetric operations: once you [sign](https://docs.aws.amazon.com/kms/latest/APIReference/API_Sign.html), you have to pass not only the signature but key id and signature type to the [verify](https://docs.aws.amazon.com/kms/latest/APIReference/API_Verify.html) API, leaving KMS users to work out how to store and pass along this metadata. The Encyption SDK has very effectively solved this problem for symmetric operations, and it would be great to have it extended to cover asymmetric operations.

**Comment by scottarc** [comment]
Hi @benkehoe,

> The Encyption SDK has very effectively solved this problem for symmetric operations, and it would be great to have it extended to cover asymmetric operations.

Are you specifically referring to **asymmetric encryption** operations for the Encryption SDK here, or do you also want to see signing operations included?

**Comment by benkehoe** [comment]
Put this on the wrong repo, opened https://github.com/awslabs/aws-encryption-sdk-specification/issues/64
