### ISSUE TITLE
Update oracle to accept messages encrypted with Raw Keyrings

### ISSUE THREAD

**Issue by MatthewBennington** [aws/aws-encryption-sdk-python#210]
Presently Encryption SDKs testing against the python decryption oracle can only test messages encrypted with the KMSKeyring. It would be a benefit to also be able to test RawKeyrings.

**Comment by mattsb42-aws** [comment]
Yup. My goal for v1 of the decrypt oracle is to support decryption manifests[1] in some way; maybe by accepting a zip file containing all relevant files?

[1] https://github.com/awslabs/aws-crypto-tools-test-vector-framework/blob/master/features/0004-awses-message-decryption.md

**Comment by farleyb-amazon** [comment]
Resolving in favor of https://github.com/aws/aws-encryption-sdk-python/issues/386
