### ISSUE TITLE
[keyring] clarify naming of AWS KMS keyring

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-python#252]
Per https://github.com/awslabs/aws-encryption-sdk-specification/issues/67, we are going to rename `KmsKeyring` to `AwsKmsKeyring` to be explicitly clear that this keyring interacts with the AWS Key Management Service, rather than some other KMS.

**Comment by acioc** [comment]
Spec issue merged. Spec issue tracking the completion of this implementation in https://github.com/awslabs/aws-encryption-sdk-specification/issues/127 (adding link here so it properly links and shows up as closed)
