### ISSUE TITLE
[keyring] convert examples to use CryptoResult rather than the old tuple syntax

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-python#266]
The top-level `encrypt` and `decrypt` APIs used to just return a tuple. In 1.5.0, that is changing to return a `CryptoResult` instance. This class unpacks like a two-member tuple, so this will not break any existing code, but since we want to encourage people to use the new interface we should show using these in the examples. This will also be necessary to demonstrate how to interact with the keyring trace once we resolve https://github.com/awslabs/aws-encryption-sdk-specification/issues/95.

**Comment by farleyb-amazon** [comment]
Closing in favor of https://github.com/aws/aws-encryption-sdk-python/issues/386
