### ISSUE TITLE
[keyring] should key names be bytes or str?

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-python#268]
I think this was an evolutionary thing caused originally by the provider info needing to be bytes, leading to the MKP key ID being bytes and then bleeding over into keyrings with key names.

We need to make sure that we are consistent with the spec and other implementations on this point, whether we accept just a string, just bytes, or either.

**Comment by MatthewBennington** [comment]
Issue #284 covers this, and ensures consistency with the spec.
