### ISSUE TITLE
[keyring] add one-way keyrings example

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-python#270]
Tracking here pending https://github.com/awslabs/aws-encryption-sdk-specification/issues/103

We should add a new canonical example: one-way keyrings.

The example scenario is that you want to make sure that a specific keyring is ONLY used on encryption and another is ONLY used on decryption. The example will demonstrate two custom one-way keyrings:

* encrypt-only
  * accepts another keyring as configuration
  * passes through to inner keyring on encrypt
  * does nothing on decrypt
* decrypt-only
  * accepts another keyring as configuration
  * does nothing on encrypt
  * passes through to inner keyring on decrypt

**Comment by farleyb-amazon** [comment]
Closing in favor of https://github.com/aws/aws-encryption-sdk-python/issues/386
