### ISSUE TITLE
Return nothing from Put Cache Entry in CMC

### ISSUE THREAD

**Issue by alex-chew** [aws/aws-encryption-sdk-python#287]
See awslabs/aws-encryption-sdk-specification#194.

Current implementation: https://github.com/aws/aws-encryption-sdk-python/blob/c9619992085d3fcaddf3addb369957b74621d705/src/aws_encryption_sdk/caches/base.py#L26-L47

**Comment by farleyb-amazon** [comment]
We have longer term plans to rework our cache APIs. Resolving.
