### ISSUE TITLE
Accept local CMC capacity value of 0

### ISSUE THREAD

**Issue by alex-chew** [aws/aws-encryption-sdk-python#289]
Follow-up to awslabs/aws-encryption-sdk-specification#166.

Current implementation: https://github.com/aws/aws-encryption-sdk-python/blob/c9619992085d3fcaddf3addb369957b74621d705/src/aws_encryption_sdk/caches/local.py#L43-L44

**Comment by farleyb-amazon** [comment]
We have longer term plans to rework our cache APIs. Resolving.
