### ISSUE TITLE
Make StrictAwsKmsMasterKeyProvider documentation clearer

### ISSUE THREAD

**Issue by acioc** [aws/aws-encryption-sdk-python#311]
Per https://github.com/aws/aws-encryption-sdk-python/issues/310 , our documentation implies that `StrictAwsKmsMasterKeyProvider` can encrypt and decrypt with alias ARNs. We should update this to make it clearer that you can only encrypt with alias ARNs. Decryption will not succeed since the alias ARN will not match the actual key ARN.

**Comment by xoob** [comment]
This issue just bit me while following the [Python SDK Example](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/python-example-code.html) where I intuitively used an alias ARN. I was able to encrypt but not decrypt, getting `DecryptKeyError: Unable to decrypt any data key`.
