### ISSUE TITLE
CryptographyDeprecationWarning with latest version of cryptography and aws-encryption-sdk

### ISSUE THREAD

**Issue by tleonhardt** [aws/aws-encryption-sdk-python#319]
I'm using the following package versions:
- aws-encryption-sdk==2.0.0
- cryptography==3.4.4

When I import a module which uses `aws_encryption_sdk`, I get the following warning:
```Python
/usr/local/lib/python3.7/site-packages/aws_encryption_sdk/internal/crypto/elliptic_curve.py:21: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import InterfaceNotImplemented, int_from_bytes, int_to_bytes, verify_interface
```

**Comment by ohadbenita** [comment]
Happens to me as well. Any update on when will it be solved? it floods our logs.

**Comment by farleyb-amazon** [comment]
Hi,

Sorry for the slow response here. We'll be fixing these warnings as part of our deprecation of Python 2, which will happen in an upcoming release. We'll update this issue once we have further details.

Thanks,
Ben

**Comment by stevenmu** [comment]
In order to solve this, install cryptography version 3.3.2
pip install cryptography==3.3.2
Worked for me.

**Comment by looselytiedshoelaces** [comment]
> pip install cryptography==3.3.2

It works! not seeing the warning now. Tho, I haven't tried the whole app yet. Hopefully, all goes well. Thanks

**Comment by farleyb-amazon** [comment]
Hey folks,

The most recent release of the Python Encryption SDK (3.0.0) no longer uses the deprecated `int_from_bytes` method. There are no breaking changes in this major version (aside from dropping support for Python 2), so as long as you're not on Python 2 you should be able to seamlessly upgrade to the most recent version and you'll no longer see these warnings.

Thanks,
Ben
