### ISSUE TITLE
Order of encrypted data keys is not preserved or respected in message header

### ISSUE THREAD

**Issue by FastLizard4** [aws/aws-encryption-sdk-python#327]
Hello there! I've encountered this issue using version 1.7 of the AWS Encryption SDK, but it looks like the issue is also present in the latest version.

In the Python implementation, it seems that the order of encrypted data keys is not being preserved in the message header. For example, in [`internal.utils.prepare_data_keys()`](https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/internal/utils/__init__.py#L114), the `encrypted_data_keys` variable is initialized to a set, not a list. Similarly, in [`internal.formatting.deserialize._deserialize_encrypted_data_keys()`](https://github.com/aws/aws-encryption-sdk-python/blob/93e464859c27e2f9f33f911680ecfd1a81c0db41/src/aws_encryption_sdk/internal/formatting/deserialize.py#L136), encrypted data keys are read out from the message header into a set.

Compare this with the Java implementation of the AWS Encryption SDK; for example, the [`EncryptionMaterials` class](https://github.com/aws/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/model/EncryptionMaterials.java#L23) or the [`DecryptionMaterialsRequest` class](https://github.com/aws/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/model/DecryptionMaterialsRequest.java), which use a list to contain the encrypted data keys for a message.

This has the implication that when using the Python implementation of the encryption SDK, the order that encrypted data keys are serialized into or deserialized from the encrypted message is unpredictable and doesn't respect the order that keys are passed into the master key provider, nor the order of the encrypted data keys within the encrypted message. As an example, this is significant when operating in an environment where all data needs to be accessible in multiple AWS regions: the local region and a geographically distinct region for disaster recovery purposes. It's desirable to always have the local region's KMS keys used first since this means that decryption will first be attempted in that local region, avoiding the additional latencies involved with cross-region access.

While preserving the order of the encrypted data keys (and thus the master keys) doesn't appear to be explicitly specified in the documentation, there are a few places that suggest that this is the intended behavior to me:
* [The AWS Encryption SDK Developer Guide PDF](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/encryption-sdk-developer-guide.pdf) on page 26 (PDF page 31) notes that, "When decrypting with an AWS KMS discovery keyring, the AWS Encryption SDK calls AWS KMS to decrypt each of the encrypted data keys in the encrypted message in the order that they appear until one succeeds."
* The Keyring Interface specification, in [the section regarding encrypting data keys](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/keyring-interface.md#encrypt-data-key), uses the terminology "*appends* the encrypted data keys to the encrypted data key list in the encryption materials" (emphasis added)
* The Structures specification, in [the section on encrypted data keys](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/structures.md#encrypted-data-keys), also calls it a "list" of encrypted data keys

The desired fix here would be to use lists in the Python implementation of the AWS Encryption SDK as well, ensuring that the order of encrypted data keys within the message header is always consistent with the order of keys in the master key providers, as well as ensuring that decryption attempts using encrypted data keys in a predictable order matching the order of the encrypted data keys in the message header.

Thank you so much for your time!

**Comment by farleyb-amazon** [comment]
Thanks for the detailed report! Your description makes sense, and we've had similar reports (https://github.com/aws/aws-encryption-sdk-python/issues/226). For now I'm going to close this out in favor of that other issue, which has a bit more discussion. Please do feel free to update that issue with any additional comments or concerns.
