### ISSUE TITLE
Why can't use in enclave

### ISSUE THREAD

**Issue by hyoer0423** [aws/aws-encryption-sdk-python#359]
### Problem:
Hello team, I try to include this aws encryption sdk into the AWS Nitro-Enclaves and use client.encrypt(source=source_plaintext, key_provider=master_key_provider) to encrypt under that environment. However, it just stuck in import aws_encryption_sdk and can't find the reason why. I also tried on the docker and works well. Moreover, i disconnect the network of docker can still work, so the problem may not because enclave is a unconnected environment. Maybe there is some problem for your cli to use in enclave environment.

**Comment by texastony** [comment]
Howdy hyoer0423,

We have managed to reproduce your issue by following the the build steps in your encr_enclave repo [1].

We Root Caused the error to be the uninitialized `urandom` based on the enclave's logs:

```
[    1.220906] random: aws-encryption-: uninitialized urandom read (24 bytes read)
```

The `aws-nitro-enclaves-sdk-c` has a similar issue [2] and the solution. One approach they recommend is to set `random.trust_cpu=on`, but I see from your enclave logs that this has already been set. The least effort solution for you is to add `rng-tools` to your dockerfile [3]. Initialize the random number generator daemon and sleep for at least 10 seconds before making any python calls:

```
rngd -r /dev/urandom; sleep 10;
```
 
Alternatively, you might consider using the docker image from the `aws-nitro-enclave-sdk-c` as your base image. See their instructions [4]. An early invocation of `aws_nitro_enclaves_library_seed_entropy` would likely address the issue.

Much Obliged for a really interesting issue,
AWS-Crypto-Tools


[1]: https://github.com/hyoer0423/encr_enclave/

[2]: https://github.com/aws/aws-nitro-enclaves-sdk-c/issues/41

[3]: https://github.com/nhorman/rng-tools

[4]: https://github.com/aws/aws-nitro-enclaves-sdk-c#linux---using-containers
