### ISSUE TITLE
Deliver keyrings for Python

### ISSUE THREAD

**Issue by farleyb-amazon** [aws/aws-encryption-sdk-python#386]
### Problem:

This is a general ticket to track delivery of keyrings in Python.

### Solution:

Implement the keyring spec as defined here: https://github.com/awslabs/aws-encryption-sdk-specification/tree/master/framework

**Comment by lucasmcdonald3** [comment]
https://github.com/aws/aws-encryption-sdk-python/commit/a7ebffef916c14eea134a017d87af020f8001c22
