### ISSUE TITLE
avoid leaving hanging object references in helper functions

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-python#44]
The `encrypt` and `decrypt` helper functions in the top-level `aws_encryption_sdk` module currently return the header object from the `EncryptionStream` objects. To avoid any possibility of those objects not being released for garbage collection because of active reference, we should copy the header object and return the copy.

**Comment by abdulsmapara** [comment]
@mattsb42-aws, I am interested in solving this issue.
Does the return value of ```encrypt``` function at https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/internal/crypto/encryption.py#L76 
and ```decrypt``` function at https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/internal/crypto/encryption.py#L135 need to be modified ?

**Comment by mattsb42-aws** [comment]
Hi @abdulsmapara, thanks for the interest!

This is referring to the top-level single-step interfaces for encrypt[1] and decrypt[2]. The concern is that the reference to the attribute on the stream object will keep the stream object around in memory. This is not a concern for the streaming interface because in that case the caller has direct control of the stream object.

Poking around at this a bit today, actually the only thing that we would need to do here is to use `copy.deepcopy` to copy the header and keyring trace objects from the managed stream before passing them to `CryptoResult`. It looks like `attrs` is already handling all the complicated bits. :)

[1] https://github.com/aws/aws-encryption-sdk-python/blob/82e21567a7111aea99a364e19842c3fa87a081bb/src/aws_encryption_sdk/__init__.py#L84-L87
[2] https://github.com/aws/aws-encryption-sdk-python/blob/82e21567a7111aea99a364e19842c3fa87a081bb/src/aws_encryption_sdk/__init__.py#L143-L146

**Comment by abdulsmapara** [comment]
I think this PR should complete the task !
