### ISSUE TITLE
Timeout for StrictAwsKmsMasterKeyProvider

### ISSUE THREAD

**Issue by ZacharyThomas** [aws/aws-encryption-sdk-python#446]
### Problem:

Frequently we provide timeouts and retries to our boto clients to retry requests. I searched through the documentation, and it seems like you can only provide a client to a `KMSMasterKeyConfig` instance, but I do not see how I could configure my 
`StrictAwsKmsMasterKeyProvider` to customize `KMSMasterKeyConfig`, without subclassing.  This is how we use the SDK now:

```
    sdk_client = EncryptionSDKClient()
    key_provider = StrictAwsKmsMasterKeyProvider(
        key_ids=[key_id],
        region_names=[settings.AWS_REGION],
    )
    if encryption_context is None:
        encryption_context = {}

    ciphertext, _ = sdk_client.encrypt(
        source=plaintext,
        key_provider=key_provider,
        encryption_context=encryption_context,
    )
```

Ideally, we would be able to use the SDKClient or KeyProvider to pass our KMS client preferences. 

### Solution:

Seems like the current issue is that the KeyProvider implements a _client method:
https://github.com/aws/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/key_providers/kms.py#L684

Which always creates / registers a client. Allowing me to pass a client in the `KMSMasterKeyProviderConfig` object should alleviate that. 

### Out of scope:

Is there anything the solution will intentionally NOT address?

[//]: #  (NOTE: If you believe this might be a security issue, please email aws-security@amazon.com instead of creating a GitHub issue. For more details, see the AWS Vulnerability Reporting Guide: https://aws.amazon.com/security/vulnerability-reporting/ )

**Comment by texastony** [comment]
Howdy @ZacharyThomas,

I apologize for our tardy response.
Please see [this PR for an example of customizing the client](https://github.com/aws/aws-encryption-sdk-python/pull/440/files).

However, your statement is correct:
> I do not see how I could configure ... without subclassing

As the AWS Encryption SDK for Python (ESDK-Python) is currently written,
you must subclass one of the exposed `KMSMasterKeyProvider`:

-   DiscoveryAwsKmsMasterKeyProvider
-   StrictAwsKmsMasterKeyProvider

Ultimately, we want to refactor the ESDK-Python,
replacing [Key Providers](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/master-key-provider-interface.md) with [Keyrings](https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/keyring-interface.md).

The KMS Keyrings have a cleaner interface for providing KMS clients.

We do not have a timeline for when this refactor will be done.

In the meantime, please,
follow your original instinct and our draft example and
subclass a KMS Master Key Provider to customize the KMS Client.

Much Obliged,
AWS Crypto Tools
