### ISSUE TITLE
Use of verify_interface

### ISSUE THREAD

**Issue by reaperhulk** [aws/aws-encryption-sdk-python#464]
Hi folks, I'm one of the developers of `pyca/cryptography`. We're planning to remove `verify_interface` (a function we've never publicly documented and is not part of our API contract) because it no longer has any use for us, but we noticed that you have two locations you currently call it in this codebase. In both cases you should be able to substitute a type check (either check the class itself or instantiate and do an `isinstance`) rather than using `verify_instance`. This will be backwards compatible to older `cryptography` and let us move forward with removal on our end.

**Comment by josecorella** [comment]
Hello @reaperhulk!

Thank you for reaching out to us to let us know about the deprecation of `verify_interface`.
I see that on the issue you mentioned we are currently blocking you, do y’all have a scheduled date for a new release of `pyca/cryptography` which deprecates this function?

Best,

**Comment by reaperhulk** [comment]
Our CI runs you as a downstream so we actually can't remove it without breaking our own CI 😄 We'd like to remove it for the next release though!

**Comment by josecorella** [comment]
@reaperhulk, 

Are y'all currently running releases on a cadence? If not, have y'all set date for the next release?

Best,

**Comment by alex** [comment]
We do not have a date set. Historically our releases happen roughly every 3 months, would suggest July/August for our next release, but we don't have a fixed release schedule.

**Comment by josecorella** [comment]
Hello @alex and @reaperhulk!

We have removed usage of `verify_interface`  from the ESDK. You should now be able to deprecate the function on your end.

Best,
