### ISSUE TITLE
Unable to decrypt any data key

### ISSUE THREAD

**Issue by careless25** [aws/aws-encryption-sdk-python#51]
code: 
```
kms_key_provider = aws_encryption_sdk.KMSMasterKeyProvider(key_ids=[
    os.environ["ENCRYPTION_KEY_ARN"]
])


def encrypt(plaintext):
    ciphertext, _ = aws_encryption_sdk.encrypt(
        source=plaintext,
        key_provider=kms_key_provider
    )

    return base64.b64encode(ciphertext)


def decrypt(ciphertext_b64):
    ciphertext = base64.b64decode(ciphertext_b64)

    plaintext, _ = aws_encryption_sdk.decrypt(            
        source=ciphertext,
        key_provider=kms_key_provider,
    )
    return plaintext
```

FYI, this is using v1.3.2.

I get the following error: 
```
Unable to decrypt any data key
```

When I print out the ciphertext I can clearly see the correct encryption key arn. So I am not sure whats wrong here.

**Comment by mattsb42-aws** [comment]
What permissions do you have to the KMS CMK? My initial suspicion is that you have `GenerateDataKey` permissions but not `Decrypt`.

If you turn on debug logging, you can see the error that the underlying KMS client gives. That can show you exactly what the KMS response is to your request.

**WARNING**: Do not post debug logs here or anywhere else public, as they contain the entire request and response header and bodies for any AWS calls. For the KMS calls we use, that will include your plaintext data key.

**Comment by careless25** [comment]
Just checked: 
```
            "Effect": "Allow",
            "Action": [
                "kms:Encrypt",
                "kms:Decrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:DescribeKey"
            ],
```

is in the policy for the role.

**Comment by mattsb42-aws** [comment]
Are those actions granted to the CMK in question? And does the CMK's key policy have a matching (or redundant) policy?

**Comment by careless25** [comment]
Hmm ok maybe I am missing something. @mattsb42-aws 
Can you send me a link which explains how I check for both of those things via the AWS console?

**Comment by mattsb42-aws** [comment]
These[1][2] are a good starting point for understanding key policies and how they can interact with IAM (or not, as the case may be).

You can find a brief description of this interchange in this post[3].

[1] https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html
[2] https://docs.aws.amazon.com/kms/latest/developerguide/iam-policies.html
[3] https://forums.aws.amazon.com/thread.jspa?threadID=280836&tstart=0&messageID=845931#845931

**Comment by careless25** [comment]
Yup you are correct, I turned on Debugging and found the following: 
```
The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.
```

so somewhere my permissions are incorrectly set.

**Comment by careless25** [comment]
@mattsb42-aws hmm I am not sure if this is the best place to continue this conversation but I am stumped. 

1. I am able to encrypt messages (since the encrypted messages are stored in our DB)
2. I am unable to decrypt using the same code. 
3. I double checked the policies for the role and the key. They allowed encrypt and decrypt operations. Just in case I changed to `kms:*` for both. 
4. The only issue I see is that the botocore session has the region set to us-east-2, whereas the key is in us-east-1. But then even 1 above shouldn't work right?

**Comment by mattsb42-aws** [comment]
To clarify, is the value stored in the `ENCRYPTION_KEY_ARN` environment variable a full CMK Arn or something else?

When `KMSMasterKeyProvider` is handling an Arn, it will automatically determine the region from the Arn and build a `KMSMasterKey` instance with a client for the correct region[1].

If you would rather continue this offline, feel free to email me at the address in my profile or PM me at this username on the AWS forums.

[1] https://github.com/awslabs/aws-encryption-sdk-python/blob/master/src/aws_encryption_sdk/key_providers/kms.py#L156-L163

**Comment by careless25** [comment]
Its a full Arn with the region name included.

**Comment by mattsb42-aws** [comment]
Hmmm, I think I would have to see code and policies to debug any further.

> The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.

^ This means that you don't have access to the CMK when you are trying to decrypt. Because of this, I still think that it is a policy issue. One thing you could look for is to make sure that there are not policies (either in IAM or the key policy) that deny access to your principal (user/role) performing decrypt operations with this key (or more generally). Deny policies always take precedent over allow policies.

**Comment by mattsb42-aws** [comment]
@careless25 Since this has been several months, I'm going to go ahead and close this assuming you figured out the issue. Feel free to re-open if you're still having an issue.
