### ISSUE TITLE
custom endpoint support for KMS master key and master key provider

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-python#52]
When the KMS master key and provider were designed, there was only one possible KMS endpoint per region. Between FIPS endpoints and VPC endpoints, that is no longer the case.

We should determine the best way to provide this configuration for these two structures.

**Comment by farleyb-amazon** [comment]
Given that keyrings are our long-term solution here, I expect that we will not backport this functionality to master key providers. Resolving.

**Comment by pencil** [comment]
@farleyb-amazon Can you please clarify? Are keyrings implemented in the Python client? If not, what's the solution in the meantime?
