### ISSUE TITLE
Wrong formatting in the deprecated python warning

### ISSUE THREAD

**Issue by ShubhamChaturvedi7** [aws/aws-encryption-sdk-python#545]
### Problem:

https://github.com/aws/aws-encryption-sdk-python/blob/f8aa29fe98d419dac916846d7ff207685ea95307/src/aws_encryption_sdk/compatability.py#L38

The _minimum_version_ and _date_ seem to have been swapped in the deprecated python warning.
### Solution:

Putting the `params["date"]` before the `minimum_version[0]` should fix the issue.

**Comment by texastony** [comment]
Addressed in main by #546 , though the issue still remains in the old branches.

**Comment by seebees** [comment]
this does not need to be backported at this time
