### ISSUE TITLE
thread safety?

### ISSUE THREAD

**Issue by gliptak** [aws/aws-encryption-sdk-python#560]
Are `aws_encryption_sdk.EncryptionSDKClient`, `aws_encryption_sdk.StrictAwsKmsMasterKeyProvider`, `aws_encryption_sdk.CachingCryptoMaterialsManager` (and related constructs) thread-safe?

I didn't see related details in the documentation, so please point me if it is available to review.

**Comment by ajewellamz** [comment]
The Python ESDK is mostly thread safe, with some caveats.
An in depth discussion can be found here 
https://github.com/aws/aws-encryption-sdk-python/issues/11#issuecomment-330716036

Specifically, note that you must create a new aws_encryption_sdk.StrictAwsKmsMasterKeyProvider for each thread, but everything else should be safe.

**Comment by gliptak** [comment]
thank you for the pointer @ajewellamz I will review guidance

**Comment by gliptak** [comment]
#562
