### ISSUE TITLE
How can I encrypt a folder?

### ISSUE THREAD

**Issue by StefanMeier12** [aws/aws-encryption-sdk-python#59]
I would like to encrypt and decrypt the EBeispielordner1 folder. It would also be interesting to have several
Can encrypt folders in a single slide, e.g.

E/Beispielordner1

E/Beispielordner2

E/Beispielordner3

I would like to start this program from the console without GUI.

Can you help me? How can I customize your code?

**Comment by mattsb42-aws** [comment]
It sounds like what you want is our CLI[1]. It will do this for you without any modification.

[1] http://aws-encryption-sdk-cli.readthedocs.io/en/latest/

**Comment by mattsb42-aws** [comment]
Closing assumed resolved. If you have any additional questions, please feel free to reopen or create a new issue.
