### ISSUE TITLE
How to get 'IV' used for encryption using kms

### ISSUE THREAD

**Issue by siriaws** [aws/aws-encryption-sdk-python#60]
How to get 'IV' used for encryption using kms?
 we are using s3 copy to redshift  using client side encryption. and s3 object need s3  data as  metadata .
the error i see is 
"error: Failed writing body (0 != 16347) Cause: S3 object encryption key iv is of invalid size. Size=17. Expected size 16"

**Comment by mattsb42-aws** [comment]
Unfortunately, the S3 encryption client and the AWS Encryption SDK do not create compatible ciphertext formats. [More on that here](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/faq.html#s3-encryption-client).

Could you describe your use case a bit more? Were the objects in S3 written by an S3  encryption client or an AWS Encryption SDK client?

**Comment by siriaws** [comment]
the objects in s3 written by an AWS Encryption SDK client.
I am using redshift  COPY command to load the  encrypted data from s3 .
To decrypt the file   redshift needs metadata from s3 objects /metadata/.
so I have to get the values  of
1. x-amz-meta-x-amz-key
2.x-amz-meta-x-amz-iv

how to obtain the value of  x-amz-meta-x-amz-iv   from aws-encryption-sdk after an object is encrypted using KMS-CMK.
I am able to get  the  value of x-amz-meta-x-amz-key using aws-encryption-sdk .

**Comment by mattsb42-aws** [comment]
The Redshift COPY command only currently works with client-side encrypted objects if they were encrypted using an S3 encryption client (and even then only in certain cases)[1]. Even if you were to pull out the relevant components of the ciphertext message that the AWS Encryption SDK creates, the ciphertexts themselves are not compatible with S3 encryption clients[2].

[1] https://docs.aws.amazon.com/redshift/latest/dg/c_loading-encrypted-files.html
[2] https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/faq.html#s3-encryption-client

**Comment by mattsb42-aws** [comment]
I'm going to go ahead and close this. If you have any other questions, please feel free to open another issue.
