### ISSUE TITLE
Issue with the /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /var/task/cryptography/hazmat/bindings/_rust.abi3.so)

### ISSUE THREAD

**Issue by surajtikoo** [aws/aws-encryption-sdk-python#609]
### Security issue notifications

If you discover a potential security issue in the AWS Encryption SDK we ask that you notify AWS Security via our [vulnerability reporting page](https://aws.amazon.com/security/vulnerability-reporting/). Please do **not** create a public GitHub issue.

### Problem:

Hi, Team I am using this sdk with Python 3.10 version and using the lastest version of cryptography. The code is breaking for the cryptography.

### Solution:

A description of the possible solution in terms of Encryption SDK architecture.

### Out of scope:

Is there anything the solution will intentionally NOT address?

[//]: #  (NOTE: If you believe this might be a security issue, please email aws-security@amazon.com instead of creating a GitHub issue. For more details, see the AWS Vulnerability Reporting Guide: https://aws.amazon.com/security/vulnerability-reporting/ )

**Comment by seebees** [comment]
This is likely due to the latest versions of `cryptography` use Rust.
Here is a link to their documentation: https://cryptography.io/en/latest/installation/#rust 

What environment are you running on?
Can you provide a stack trace?

**Comment by seebees** [comment]
Feel free to re-open if needed.
