### ISSUE TITLE
Create release tags for all PyPI releases

### ISSUE THREAD

**Issue by JonathanHuot** [aws/aws-encryption-sdk-python#81]
Pypi is providing almost 9 different versions of `aws-encryption-sdk` but only one (1.3.0) is tagged in Git, and available in the Github "Releases" tab.

It would be great for the users of the SDK to see the releases in the source code and make it available in the Github "Releases". Or disable this tab if not used.

It makes the wrong assumption that the latest release was the 1.3.0 (2017) while latest commits are showing an active project.

**Comment by mattsb42-aws** [comment]
This is a good call-out, thanks for raising it.

This has been an oversight on our part, not making tags when we push releases.
